version: 0.2

env:
    variables:
        NODE_ENV: 'development'

phases:
    install:
        runtime-versions:
            nodejs: 12

    pre_build:
        commands:
            - echo Installing dependencies
            - yarn install

    build:
        commands:
            - echo Entered build phase
            - yarn build

    post_build:
        commands:
            - echo "Remove files we do not want to deploy"
            - rm -rf node_modules .git
            - echo Build completed on $(date)

artifacts:
    files:
        - '**/*'
    name: app-hub-$(date +%Y-%m-%d)
