export const APPS_ALL_LOAD = 'APPS_ALL_LOAD';
export const APPS_ALL_LOADED = 'APPS_ALL_LOADED';
export const APPS_ALL_ERROR = 'APPS_ALL_ERROR';

export const APPS_APPROVED_LOAD = 'APPS_APPROVED_LOAD';
export const APPS_APPROVED_ERROR = 'APPS_APPROVED_ERROR';
export const APPS_APPROVED_LOADED = 'APPS_APPROVED_LOADED';


export const APPROVE_APP = 'APPROVE_APP';
export const APPROVE_APP_SUCCESS = 'APPROVE_APP_SUCCESS';
export const APPROVE_APP_ERROR = 'APPROVE_APP_ERROR';


export const USER_LOAD = 'USER_LOAD';
export const USER_LOADED = 'USER_LOADED';
export const USER_ERROR = 'USER_ERROR';

export const USER_APPS_LOAD = 'USER_APPS_LOAD';
export const USER_APPS_LOADED = 'USER_APPS_LOADED';
export const USER_APPS_ERROR = 'USER_APPS_ERROR';