export const APPS_ALL_LOAD = 'APPS_ALL_LOAD'
export const APPS_ALL_LOADED = 'APPS_ALL_LOADED'
export const APPS_ALL_ERROR = 'APPS_ALL_ERROR'

export const APPS_APPROVED_LOAD = 'APPS_APPROVED_LOAD'
export const APPS_APPROVED_ERROR = 'APPS_APPROVED_ERROR'
export const APPS_APPROVED_LOADED = 'APPS_APPROVED_LOADED'

export const APP_LOAD = 'APP_LOAD'
export const APP_LOADED = 'APP_LOADED'
export const APP_ERROR = 'APP_ERROR'

export const APP_ADD = 'APP_ADD'
export const APP_ADD_SUCCESS = 'APP_ADD_SUCCESS'
export const APP_ADD_ERROR = 'APP_ADD_ERROR'

export const SET_APPROVAL_APP = 'SET_APPROVAL_APP'
export const SET_APPROVAL_APP_SUCCESS = 'SET_APPROVAL_APP_SUCCESS'
export const SET_APPROVAL_APP_ERROR = 'SET_APPROVAL_APP_ERROR'

export const USER_LOAD = 'USER_LOAD'
export const USER_LOADED = 'USER_LOADED'
export const USER_ERROR = 'USER_ERROR'

export const USER_APPS_LOAD = 'USER_APPS_LOAD'
export const USER_APPS_LOADED = 'USER_APPS_LOADED'
export const USER_APPS_ERROR = 'USER_APPS_ERROR'

export const USER_AUTHENTICATED = 'USER_AUTHENTICATED'
export const USER_LOGOUT = 'USER_LOGOUT'

export const OPEN_DIALOG = 'OPEN_DIALOG'
export const CLOSE_DIALOG = 'CLOSE_DIALOG'

export const APP_VERSION_ADD = 'APP_VERSION_ADD'
export const APP_VERSION_ADD_SUCCESS = 'APP_VERSION_ADD_SUCCESS'
export const APP_VERSION_ADD_ERROR = 'APP_VERSION_ADD_ERROR'

export const APP_VERSION_DELETE = 'APP_VERSION_DELETE'
export const APP_VERSION_DELETE_SUCCESS = 'APP_VERSION_DELETE_SUCCESS'
export const APP_VERSION_DELETE_ERROR = 'APP_VERSION_DELETE_ERROR'

export const APP_VERSION_EDIT = 'APP_VERSION_EDIT'
export const APP_VERSION_EDIT_SUCCESS = 'APP_VERSION_EDIT_SUCCESS'
export const APP_VERSION_EDIT_ERROR = 'APP_VERSION_EDIT_ERROR'

export const APP_EDIT = 'APP_EDIT'
export const APP_EDIT_SUCCESS = 'APP_EDIT_SUCCESS'
export const APP_EDIT_ERROR = 'APP_EDIT_ERROR'

export const APP_DELETE = 'APP_DELETE'
export const APP_DELETE_SUCCESS = 'APP_DELETE_SUCCESS'
export const APP_DELETE_ERROR = 'APP_DELETE_ERROR'

export const APP_IMAGES_ADD = 'APP_IMAGES_ADD'
export const APP_IMAGES_ADD_SUCCESS = 'APP_IMAGES_ADD_SUCCESS'
export const APP_IMAGES_ADD_ERROR = 'APP_IMAGES_ADD_ERROR'

export const APP_IMAGE_ADD = 'APP_IMAGE_ADD'
export const APP_IMAGE_ADD_SUCCESS = 'APP_IMAGE_ADD_SUCCESS'
export const APP_IMAGE_ADD_ERROR = 'APP_IMAGE_ADD_ERROR'

export const APP_IMAGE_EDIT = 'APP_IMAGE_EDIT'
export const APP_IMAGE_EDIT_SUCCESS = 'APP_IMAGE_EDIT_SUCCESS'
export const APP_IMAGE_EDIT_ERROR = 'APP_IMAGE_EDIT_ERROR'

export const APP_IMAGE_DELETE = 'APP_IMAGE_DELETE'
export const APP_IMAGE_DELETE_SUCCESS = 'APP_IMAGE_DELETE_SUCCESS'
export const APP_IMAGE_DELETE_ERROR = 'APP_IMAGE_DELETE_ERROR'

export const APP_IMAGE_SET_LOGO = 'APP_IMAGE_SET_LOGO'
export const APP_IMAGE_SET_LOGO_SUCCESS = 'APP_IMAGE_SET_LOGO_SUCCESS'
export const APP_IMAGE_SET_LOGO_ERROR = 'APP_IMAGE_SET_LOGO_ERROR'

export const SNACKBAR_EMPTY = 'SNACKBAR_EMPTY'
