export const APPS_ALL_LOAD = 'APPS_ALL_LOAD'
export const APPS_ALL_LOADED = 'APPS_ALL_LOADED'
export const APPS_ALL_ERROR = 'APPS_ALL_ERROR'

export const APP_LOAD = 'APP_LOAD'
export const APP_LOADED = 'APP_LOADED'
export const APP_ERROR = 'APP_ERROR'

export const APP_ADD = 'APP_ADD'
export const APP_ADD_SUCCESS = 'APP_ADD_SUCCESS'
export const APP_ADD_ERROR = 'APP_ADD_ERROR'

export const SET_APPROVAL_APP = 'SET_APPROVAL_APP'
export const SET_APPROVAL_APP_SUCCESS = 'SET_APPROVAL_APP_SUCCESS'
export const SET_APPROVAL_APP_ERROR = 'SET_APPROVAL_APP_ERROR'

export const USER_LOAD = 'USER_LOAD'
export const USER_LOADED = 'USER_LOADED'
export const USER_ERROR = 'USER_ERROR'

export const USER_APPS_LOAD = 'USER_APPS_LOAD'
export const USER_APPS_LOADED = 'USER_APPS_LOADED'
export const USER_APPS_ERROR = 'USER_APPS_ERROR'

export const USER_AUTHENTICATED = 'USER_AUTHENTICATED'
export const USER_LOGOUT = 'USER_LOGOUT'

export const OPEN_DIALOG = 'OPEN_DIALOG'
export const CLOSE_DIALOG = 'CLOSE_DIALOG'

export const APP_VERSION_ADD = 'APP_VERSION_ADD'
export const APP_VERSION_ADD_SUCCESS = 'APP_VERSION_ADD_SUCCESS'
export const APP_VERSION_ADD_ERROR = 'APP_VERSION_ADD_ERROR'

export const APP_VERSION_DELETE = 'APP_VERSION_DELETE'
export const APP_VERSION_DELETE_SUCCESS = 'APP_VERSION_DELETE_SUCCESS'
export const APP_VERSION_DELETE_ERROR = 'APP_VERSION_DELETE_ERROR'

export const APP_VERSION_EDIT = 'APP_VERSION_EDIT'
export const APP_VERSION_EDIT_SUCCESS = 'APP_VERSION_EDIT_SUCCESS'
export const APP_VERSION_EDIT_ERROR = 'APP_VERSION_EDIT_ERROR'

export const APP_EDIT = 'APP_EDIT'
export const APP_EDIT_SUCCESS = 'APP_EDIT_SUCCESS'
export const APP_EDIT_ERROR = 'APP_EDIT_ERROR'

export const APP_DELETE = 'APP_DELETE'
export const APP_DELETE_SUCCESS = 'APP_DELETE_SUCCESS'
export const APP_DELETE_ERROR = 'APP_DELETE_ERROR'

export const APP_IMAGES_ADD = 'APP_IMAGES_ADD'
export const APP_IMAGES_ADD_SUCCESS = 'APP_IMAGES_ADD_SUCCESS'
export const APP_IMAGES_ADD_ERROR = 'APP_IMAGES_ADD_ERROR'

export const APP_IMAGE_ADD = 'APP_IMAGE_ADD'
export const APP_IMAGE_ADD_SUCCESS = 'APP_IMAGE_ADD_SUCCESS'
export const APP_IMAGE_ADD_ERROR = 'APP_IMAGE_ADD_ERROR'

export const APP_IMAGE_EDIT = 'APP_IMAGE_EDIT'
export const APP_IMAGE_EDIT_SUCCESS = 'APP_IMAGE_EDIT_SUCCESS'
export const APP_IMAGE_EDIT_ERROR = 'APP_IMAGE_EDIT_ERROR'

export const APP_IMAGE_DELETE = 'APP_IMAGE_DELETE'
export const APP_IMAGE_DELETE_SUCCESS = 'APP_IMAGE_DELETE_SUCCESS'
export const APP_IMAGE_DELETE_ERROR = 'APP_IMAGE_DELETE_ERROR'

export const APP_IMAGE_SET_LOGO = 'APP_IMAGE_SET_LOGO'
export const APP_IMAGE_SET_LOGO_SUCCESS = 'APP_IMAGE_SET_LOGO_SUCCESS'
export const APP_IMAGE_SET_LOGO_ERROR = 'APP_IMAGE_SET_LOGO_ERROR'

export const SNACKBAR_EMPTY = 'SNACKBAR_EMPTY'

export const CHANNELS_LOAD_BEGIN = 'CHANNELS_LOAD_BEGIN'
export const CHANNELS_LOAD_SUCCESS = 'CHANNELS_LOAD_SUCCESS'
export const CHANNELS_LOAD_ERROR = 'CHANNELS_LOAD_ERROR'

export const ORGANISATIONS_SEARCH = 'ORGANISATIONS_SEARCH'
export const ORGANISATIONS_SEARCH_SUCCESS = 'ORGANISATIONS_SEARCH_SUCCESS'
export const ORGANISATIONS_SEARCH_ERROR = 'ORGANISATIONS_SEARCH_ERROR'

export const ORGANISATIONS_LOAD = 'ORGANISATIONS_LOAD'
export const ORGANISATIONS_LOAD_SUCCESS = 'ORGANISATIONS_LOAD_SUCCESS'
export const ORGANISATIONS_LOAD_ERROR = 'ORGANISATIONS_LOAD_ERROR'

export const ORGANISATION_LOAD = 'ORGANISATION_LOAD'
export const ORGANISATION_LOAD_SUCCESS = 'ORGANISATION_LOAD_SUCCESS'
export const ORGANISATION_LOAD_ERROR = 'ORGANISATION_LOAD_ERROR'

export const ORGANISATION_MEMBER_ADD = 'ORGANISATION_MEMBER_ADD'
export const ORGANISATION_MEMBER_ADD_SUCCESS = 'ORGANISATION_MEMBER_ADD_SUCCESS'
export const ORGANISATION_MEMBER_ADD_ERROR = 'ORGANISATION_MEMBER_ADD_ERROR'

export const ORGANISATION_MEMBER_REMOVE = 'ORGANISATION_MEMBER_REMOVE'
export const ORGANISATION_MEMBER_REMOVE_SUCCESS =
    'ORGANISATION_MEMBER_REMOVE_SUCCESS'
export const ORGANISATION_MEMBER_REMOVE_ERROR =
    'ORGANISATION_MEMBER_REMOVE_ERROR'

export const ORGANISATION_ADD = 'ORGANISATION_ADD'
export const ORGANISATION_ADD_SUCCESS = 'ORGANISATION_ADD_SUCCESS'
export const ORGANISATION_ADD_ERROR = 'ORGANISATION_ADD_ERROR'

export const ME_LOAD = 'ME_LOAD'
export const ME_LOAD_SUCCESS = 'ME_LOAD_SUCCESS'
export const ME_LOAD_ERROR = 'ME_LOAD_ERROR'

export const ORGANISATION_EDIT = 'ORGANISATION_EDIT'
export const ORGANISATION_EDIT_SUCCESS = 'ORGANISATION_EDIT_SUCCESS'
export const ORGANISATION_EDIT_ERROR = 'ORGANISATION_EDIT_ERROR'
