module.exports = [
    require('./handlers/getAllApprovedApps'),
    require('./handlers/getAllApps'),
    require('./handlers/getSingleApp'),
    require('./handlers/getMyApps'),
    require('./handlers/getAppFile'),
    require('./handlers/setApprovalStatus'),
    require('./handlers/deleteApp'),
    require('./handlers/getAppMedia'),
    require('./handlers/editApp'),
    require('./handlers/editAppVersion'),
    require('./handlers/editImage'),
    require('./handlers/uploadImageToApp'),
    require('./handlers/deleteImage'),
    require('./handlers/createAppVersion'),
    require('./handlers/deleteAppVersion'),
]
