module.exports = {
    RTAvatar: { avatar: "_3OjJz", image: "_2Ueo9", letter: "_26GdB" },
    RTAppBar: {
        appBar: "_3Py1Z",
        scrollHide: "PyOfn",
        flat: "_1J9he",
        fixed: "_2dwFx",
        inner: "lGWLJ",
        title: "_37vtt",
        leftIcon: "_30BcY",
        rightIcon: "_1hv3P"
    },
    RTButton: {
        button: "_2Agdx",
        rippleWrapper: "_3AVBi",
        squared: "_2GH_L",
        icon: "_3aBSX",
        solid: "_1ZxqC",
        raised: "_221ic _2Agdx _2GH_L _1ZxqC",
        flat: "_1jWAQ _2Agdx _2GH_L",
        floating: "_3IRMZ _2Agdx _1ZxqC",
        mini: "_2DCN-",
        toggle: "hC5Z2 _2Agdx",
        primary: "_3tTAW",
        accent: "_2wp6F",
        neutral: "_2CPs4",
        inverse: "_2SPZr"
    },
    RTRipple: {
        rippleWrapper: "_16N7o",
        ripple: "_3SV_u",
        rippleRestarting: "_2OZWa",
        rippleActive: "_3O2Ue"
    },
    RTCard: {
        card: "_8pay8",
        raised: "_1AHwB",
        cardMedia: "_3Yc6z",
        wide: "_35NNe",
        square: "_1HBxg",
        content: "ewAVM",
        contentOverlay: "_1bBKz",
        cardTitle: "_1dU3o",
        cardActions: "ZoLIG",
        cardText: "K_kzH",
        title: "_3qCP3",
        subtitle: "_3p3mO",
        large: "_2iwOK",
        small: "_1RHxe"
    },
    RTDatePicker: {
        input: "_2ISvI",
        disabled: "Cf3yF",
        inputElement: "x7MhN",
        header: "_2vLUd",
        year: "_1VWY-",
        date: "_3K2Ws",
        calendarWrapper: "_1t-4v",
        yearsDisplay: "_2OzvT",
        monthsDisplay: "_2DDdC",
        dialog: "_3fCV6",
        button: "_2hL6u",
        calendar: "_1X9ls",
        prev: "Nv9Bc",
        next: "_3iPkS",
        title: "_2ESpD",
        years: "zEdgW",
        active: "_1pjXb",
        week: "PcByv",
        days: "_1qh3T",
        day: "_2qF_L",
        month: "_1hSm5",
        slideRightEnter: "Rk89h",
        slideRightLeave: "_1nam4",
        slideRightEnterActive: "m5B3T",
        slideRightLeaveActive: "_2bZap",
        slideLeftEnter: "bGml_",
        slideLeftLeave: "_2WGqM",
        slideLeftEnterActive: "_3Ghls",
        slideLeftLeaveActive: "_2WLHG"
    },
    RTInput: {
        input: "lFVgC",
        withIcon: "_1nKdf",
        icon: "_3ga1V",
        inputElement: "_4bZUj",
        bar: "_3FySS",
        label: "_34120",
        fixed: "GRQEP",
        required: "_2G0aY",
        hint: "bMyi_",
        filled: "_34NWn",
        error: "_2k5Jz",
        counter: "_1oTuT",
        disabled: "_3ZfJq",
        errored: "_2s74E",
        hidden: "_2gAMv"
    },
    RTDialog: {
        wrapper: "_3nrqp",
        dialog: "_3lw90",
        active: "_3ea_1",
        small: "_38VTT",
        normal: "_1K3iz",
        large: "_10LcP",
        fullscreen: "_3tLXQ",
        title: "_2J-aP",
        body: "_1Ivuq",
        navigation: "wgwdj",
        button: "_22_c6"
    },
    RTOverlay: { overlay: "_2LA9x", active: "_1mb5R" },
    RTDrawer: {
        wrapper: "_3eRY8",
        drawer: "_1sAOY",
        active: "EWFXC",
        right: "_2-4-H",
        left: "FKhpR"
    },
    RTDropdown: {
        dropdown: "ZzBNK",
        active: "_1DQ-E",
        values: "_2767w",
        label: "_2KjGM",
        value: "_6c1D5",
        up: "_1OA-G",
        disabled: "_1skVH",
        field: "d5bru",
        errored: "_3dZUG",
        templateValue: "_6dCtT",
        required: "_1j4LX",
        error: "fySw3",
        selected: "_3uiEo"
    },
    RTList: {
        list: "caNNQ",
        divider: "_2Jg3-",
        subheader: "q2l8C",
        inset: "_1HHo_",
        listItem: "ni6RH",
        ripple: "_2mi0Y",
        item: "_2GtDw",
        selectable: "_1OoR-",
        disabled: "_38DD6",
        checkboxItem: "OVyge",
        checkbox: "_3SG-0",
        left: "bHOJq",
        right: "OQ3Je",
        itemAction: "VB7pN",
        itemContentRoot: "_2FBCh",
        large: "EO5bo",
        itemText: "_12FqV",
        primary: "_3SxNr"
    },
    RTCheckbox: {
        field: "_3Tq32",
        ripple: "_2NWrZ",
        text: "dXU7C",
        input: "_271V1",
        check: "_1CXAo",
        checked: "nSz7s",
        "checkmark-expand": "_3GU9D",
        disabled: "_2jVLS"
    },
    RTLink: { icon: "_1-mD4", link: "_1Od3D", active: "_3blKB" },
    RTMenu: {
        iconMenu: "_2aMxm",
        icon: "_1b8Ml",
        menu: "_1gvr5",
        topLeft: "SYeW8",
        outline: "_2PdTB",
        topRight: "DFQvY",
        bottomLeft: "_3i7lA",
        bottomRight: "_3q-zB",
        static: "_2xf5n",
        menuInner: "_2t8UE",
        rippled: "_3o1JI",
        active: "_2Cekp",
        menuItem: "lyzBJ",
        disabled: "zGTpA",
        selected: "_2-j_P",
        ripple: "_2m_Cl",
        caption: "_3MsfE",
        shortcut: "_1anRY",
        menuDivider: "VX5Lv"
    },
    RTNavigation: { horizontal: "_1MJ9B", vertical: "xUlwz" },
    RTProgressBar: {
        linear: "_3vxHj",
        "linear-indeterminate-bar": "_1cU21",
        indeterminate: "_1gPzb",
        value: "I0PhY",
        buffer: "SzbNd",
        circular: "_2j3vC",
        "circular-indeterminate-bar-rotate": "zfZzh",
        "circular-indeterminate-bar-dash": "_3DSlU",
        colors: "Z_PDt",
        circle: "DlWjM",
        path: "_1xZSU",
        multicolor: "_3XHT8"
    },
    RTSnackbar: {
        snackbar: "zDi3X",
        accept: "_2Y0Cy",
        button: "_2pCxU",
        warning: "_2li3o",
        cancel: "_3731C",
        active: "_38CsO",
        label: "_1JIbY"
    },
    RTLayout: {
        layout: "wiKya",
        panel: "_3aW3s",
        bodyScroll: "_2uzOU",
        sidebarDrawer: "_2kCN0",
        navDrawerDrawer: "Cte92",
        pinned: "qf0ha",
        clipped: "_1y5eh",
        appbarInner: "_1S9wz",
        appbarFixed: "_2Q-xL",
        appbarAppBar: "F9Fy2",
        navDrawerPinned: "_2eOy5",
        appbarLeftIcon: "fZ13o",
        navDrawerClipped: "_2kROG",
        navDrawerWrapper: "_2gpOZ",
        sidebarPinned: "_3yo9c",
        sidebarClipped: "_1paQt",
        sidebarWrapper: "_1TUxm",
        sidebarWidth1: "_1EWpa",
        sidebarWidth2: "_37z5O",
        sidebarWidth3: "_24Dtc",
        sidebarWidth4: "_28mqi",
        sidebarWidth5: "K39iB",
        sidebarWidth6: "_2PjBX",
        sidebarWidth7: "_16Oxc",
        sidebarWidth8: "_3fr9v",
        sidebarWidth9: "iF_4K",
        sidebarWidth10: "_3mnwI",
        sidebarWidth11: "_2uccf",
        sidebarWidth12: "_1pU-9",
        sidebarWidth25: "_10h-v",
        sidebarWidth33: "BYRr2",
        sidebarWidth50: "_2L3ft",
        sidebarWidth66: "_31jol",
        sidebarWidth75: "_2Xvmh",
        sidebarWidth100: "_3T7B6"
    },
    RTTooltip: {
        tooltip: "_1v8bI",
        tooltipActive: "_2xWjx",
        tooltipTop: "_1PfOK",
        tooltipLeft: "_3uj3d",
        tooltipRight: "_3UQWj",
        tooltipInner: "_9q2WH"
    }
};
